Repository SaraDahman/instagram-clone, pull requests merged in 2023-01, with the labels that each got.

#75 Designed user info section, and handled the returned data from the API
  client/src/assets/images/user.png
  client/src/component/EmptyPosts/style.css
  client/src/component/Footer/index.tsx
  client/src/component/Footer/style.css
  client/src/component/Post/index.tsx
  client/src/component/Profile/Index.tsx
  client/src/component/Profile/style.css
  client/src/component/ProfileUserInfo/index.tsx
  client/src/component/ProfileUserInfo/style.css
  client/src/component/Saved/index.tsx
  client/src/component/Suggestions/index.tsx
  client/src/data/FakeUsersData.ts
  client/src/interfaces/IProfileData.ts
  client/src/interfaces/IUserInfoProps.ts
  client/src/interfaces/index.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.service.ts
Labels: Awaiting review

#76 refactor code
  server/src/modules/user/user.service.ts
Labels: Done

#77 created Loading component and imported it in all required components
  client/src/component/ImageSlideShow/index.tsx
  client/src/component/Loading/Index.tsx
  client/src/component/Loading/style.css
  client/src/component/PostsContainer/index.tsx
  client/src/component/Profile/Index.tsx
  client/src/component/ProfilePosts/index.tsx
  client/src/component/stories/index.tsx
Labels: Approved

#80 Handled User Posts
  client/src/component/Profile/Index.tsx
  client/src/component/ProfilePosts/index.tsx
  client/src/component/Saved/index.tsx
  client/src/interfaces/IProfilePosts.ts
  client/src/interfaces/index.ts
  server/src/modules/posts/posts.controller.ts
  server/src/modules/posts/posts.service.ts
Labels: Approved

#81 Added Image component and handle display number of comments and likes over each post
  client/src/component/ProfilePosts/index.tsx
  client/src/component/ProfilePosts/style.css
  client/src/interfaces/IProfilePosts.ts
  server/src/modules/posts/posts.service.ts
Labels: Awaiting review

#83 No Posts case for other users
  client/src/component/EmptyPosts/index.tsx
  client/src/component/Profile/Index.tsx
  client/src/interfaces/IEmptyPostProps.ts
Labels: Awaiting review

#90 Handled Bookmarks Request
  client/src/component/Profile/Index.tsx
  client/src/component/ProfilePosts/index.tsx
  client/src/component/Saved/index.tsx
  client/src/interfaces/IProfilePosts.ts
  server/src/modules/bookmarks/bookmarks.service.ts
  server/src/modules/posts/posts.service.ts
Labels: Approved

#91 [react, server] handle route [update]users/:id and handle request in client side
  .vscode/settings.json
  client/src/assets/images/user.png
  client/src/component/EditProfile/index.tsx
  client/src/component/EditProfile/style.css
  client/src/component/ProfileUserInfo/index.tsx
  client/src/component/ProfileUserInfo/style.css
  client/src/component/index.ts
  client/src/index.tsx
  client/src/interfaces/IContext.ts
  client/src/pages/Settings/index.tsx
  client/src/pages/Settings/style.css
  client/src/pages/index.ts
  client/src/router/index.tsx
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/modules/index.ts
  server/src/modules/upload/cloudinary.controller.ts
  server/src/modules/upload/cloudinary.module.ts
  server/src/modules/upload/cloudinary.provider.ts
  server/src/modules/upload/cloudinary.service.ts
  server/src/modules/user/dto/create-user.dto.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.service.ts
Labels: Approved

#87 53 create add post popup
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/component/AddPosts/icons.tsx
  client/src/component/AddPosts/index.tsx
  client/src/component/AddPosts/style.css
  client/src/component/CropImage/NextArrow.tsx
  client/src/component/CropImage/PrevArrow.tsx
  client/src/component/CropImage/handleCrop.ts
  client/src/component/CropImage/index.tsx
  client/src/component/CropImage/style.css
  client/src/component/DropZone/icons.tsx
  client/src/component/DropZone/index.tsx
  client/src/component/DropZone/style.css
  client/src/component/EditProfile/index.tsx
  client/src/component/ImageLoading/Loading.tsx
  client/src/component/PrepareSharingPost/index.tsx
  client/src/component/PrepareSharingPost/style.css
  client/src/component/ProfilePosts/style.css
  client/src/component/index.ts
  client/src/interfaces/ICropsProps.ts
  client/src/interfaces/index.ts
  client/src/pages/Home/index.tsx
  client/src/react-app-env.d.ts
  server/src/core/Pipes/FileSizeValidation.pipe.ts
  server/src/modules/posts/dto/create-post.dto.ts
  server/src/modules/upload/cloudinary.controller.ts
Labels: Approved

#95 84 create following popup
  client/src/component/FollowPopUp/Person.tsx
  client/src/component/FollowPopUp/index.tsx
  client/src/component/FollowPopUp/style.css
  client/src/component/Profile/Index.tsx
  client/src/component/ProfileUserInfo/index.tsx
  client/src/component/ProfileUserInfo/style.css
  client/src/interfaces/IFollowPopUp.ts
  client/src/interfaces/IFollowers.ts
  client/src/interfaces/index.ts
  server/src/modules/following/following.controller.ts
  server/src/modules/following/following.service.ts
Labels: Awaiting review
